### ISSUE TITLE
Error in the exporter when I use the AWS user credentials

### ISSUE THREAD

**Issue by vladsamoylik** [mr-karan/aws-dc-exporter#1]
I am getting an error in the exporter when I use the AWS user credentials (Access key ID and Secret access key). 
Operating system Centos 8 Stream.
The error is repeated when using assembly from source.

journalctl log:
```
Feb 21 13:43:34 monitor-1.xxx.com aws-dc-exporter[49871]: 2021/02/21 13:43:34 http: panic serving [::1]:53508: runtime error: invalid memory address or nil pointer dereference
Feb 21 13:43:34 monitor-1.xxx.com aws-dc-exporter[49871]: goroutine 6 [running]:
Feb 21 13:43:34 monitor-1.xxx.com aws-dc-exporter[49871]: net/http.(*conn).serve.func1(0xc000113860)
Feb 21 13:43:34 monitor-1.xxx.com aws-dc-exporter[49871]:         /usr/lib/golang/src/net/http/server.go:1808 +0x13e
Feb 21 13:43:34 monitor-1.xxx.com aws-dc-exporter[49871]: panic(0x875f20, 0xcec950)
Feb 21 13:43:34 monitor-1.xxx.com aws-dc-exporter[49871]:         /usr/lib/golang/src/runtime/panic.go:975 +0x3e3
Feb 21 13:43:34 monitor-1.xxx.com aws-dc-exporter[49871]: main.(*Hub).Collect(0xc0001e58c0, 0xc0000630c0, 0xa1df00, 0xc000214b10, 0xc00006c690)
Feb 21 13:43:34 monitor-1.xxx.com aws-dc-exporter[49871]:         /root/aws-dc-exporter/exporter.go:39 +0x25a
Feb 21 13:43:34 monitor-1.xxx.com aws-dc-exporter[49871]: main.main.func2(0xa217c0, 0xc0002202a0, 0xc00011b000)
Feb 21 13:43:34 monitor-1.xxx.com aws-dc-exporter[49871]:         /root/aws-dc-exporter/main.go:76 +0xcf
Feb 21 13:43:34 monitor-1.xxx.com aws-dc-exporter[49871]: net/http.HandlerFunc.ServeHTTP(0xc000214b20, 0xa217c0, 0xc0002202a0, 0xc00011b000)
Feb 21 13:43:34 monitor-1.xxx.com aws-dc-exporter[49871]:         /usr/lib/golang/src/net/http/server.go:2053 +0x44
Feb 21 13:43:34 monitor-1.xxx.com aws-dc-exporter[49871]: net/http.(*ServeMux).ServeHTTP(0xc000062ec0, 0xa217c0, 0xc0002202a0, 0xc00011b000)
Feb 21 13:43:34 monitor-1.xxx.com aws-dc-exporter[49871]:         /usr/lib/golang/src/net/http/server.go:2428 +0x1a5
Feb 21 13:43:34 monitor-1.xxx.com aws-dc-exporter[49871]: net/http.serverHandler.ServeHTTP(0xc0002201c0, 0xa217c0, 0xc0002202a0, 0xc00011b000)
Feb 21 13:43:34 monitor-1.xxx.com aws-dc-exporter[49871]:         /usr/lib/golang/src/net/http/server.go:2848 +0xa3
Feb 21 13:43:34 monitor-1.xxx.com aws-dc-exporter[49871]: net/http.(*conn).serve(0xc000113860, 0xa227c0, 0xc000062f80)
Feb 21 13:43:34 monitor-1.xxx.com aws-dc-exporter[49871]:         /usr/lib/golang/src/net/http/server.go:1936 +0x86c
Feb 21 13:43:34 monitor-1.xxx.com aws-dc-exporter[49871]: created by net/http.(*Server).Serve
Feb 21 13:43:34 monitor-1.xxx.com aws-dc-exporter[49871]:         /usr/lib/golang/src/net/http/server.go:2974 +0x361

```

**Comment by mr-karan** [comment]
> AWS user credentials (Access key ID and Secret access key).

Via ENV Variables or credentials file?

**Comment by vladsamoylik** [comment]
Via credentials file

**Comment by mr-karan** [comment]
@vladsamoylik Okay. I assume some of the fields here are nil for you: https://github.com/mr-karan/aws-dc-exporter/blob/master/exporter.go#L39

Will need to add a check before dereferencing it.

**Comment by vladsamoylik** [comment]
Thank! It all worked!

**Comment by vladsamoylik** [comment]
I removed field "PartnerName" and it worked. Thank!

**Comment by sergey-safarov** [comment]
Could you also reopen this ticket because a null check still required to prevent crash.
